

name: pnpm Example Workflow
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL : ${{ secrets.DATABASE_URL }}
      NEXT_PUBLIC_SUPABASE_URL : ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_KEY : ${{ secrets.NEXT_PUBLIC_SUPABASE_KEY }}
      NEXT_PUBLIC_SUPABASE_BUCKET : ${{ secrets.NEXT_PUBLIC_SUPABASE_BUCKET }}
      GOOGLE_ID : ${{ secrets.GOOGLE_ID }}
      GOOGLE_SECRET : ${{ secrets.GOOGLE_SECRET }}
      NEXTAUTH_SECRET : ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL : ${{ secrets.NEXTAUTH_URL }}

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Debug Environment Variables
      run: |
        echo "NEXT_PUBLIC_SUPABASE_URL: $NEXT_PUBLIC_SUPABASE_URL"

    - name: Build and Deploy

      run: npm run build

      # - run: pnpm ci // should be use but dont work for now
    - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
    - run: pnpm run build #--if-present
    - run: pnpm test


